server:
  port: 8181


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: company
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "b01064794472"
    password: "wldudwldud0310!"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true







